version: '3.9'

services:
  php:
    build:
      context: ./php
    container_name: php-container
    volumes:
      - ~/codespace/php/phpworks:/var/www/html:rw,delegated
    depends_on:
      - db
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx-container
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ~/codespace/php/phpworks:/var/www/html:rw,delegated
    ports:
      - "8080:80"
    depends_on:
      - php
    networks:
      - app-network

  db:
    image: mysql:8.0
    container_name: db-container
    environment:
      MYSQL_ROOT_PASSWORD: amar123
      MYSQL_DATABASE: amardb
      MYSQL_USER: amar
      MYSQL_PASSWORD: amar123
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "3306:3306"
    networks:
      - app-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  db_data:

networks:
  app-network:
    driver: bridge
